export const TEST_PRODUCTS = [
  {
    id: 1111,
    ownerId: '10',
    title: 'Test product 1',
    description:
      'Test product description Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'Lviv',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      id: '10',
      email: 'testuser@gamil.com',
      fullName: 'Test User 1 ',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1112,
    ownerId: '20',
    title: 'Test product 2',
    description:
      'Test product description Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'Ivano-Fran.',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User 2',
      id: '20',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1113,
    ownerId: '10',
    title: 'Test product 3',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'Ternopil',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User 3 ',
      id: '30',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: Date.now() + 3,
    ownerId: '30',
    title: 'Test product 4',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User 4',
      id: '40',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1114,
    ownerId: '10',
    title: 'Test product H',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1115,
    ownerId: '10',
    title: 'Test product',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1116,
    ownerId: '10',
    title: 'Test product',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1117,
    ownerId: '10',
    title: 'Test product',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1118,
    ownerId: '10',
    title: 'Test product',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 332,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 1119,
    ownerId: '33',
    title: 'Test product!!!!',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 312,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '33',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: '',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
  {
    id: 101010,
    ownerId: '10',
    title: 'Test product',
    description: 'Test product description',
    photos: [
      'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
    ],
    location: 'ladssd',
    price: 82,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  },
];

export function createNewProduct(body) {
  const newProduct = {
    id: Date.now(),
    ownerId: '10',
    title: body.title,
    description: body.description,
    photos: body.images,
    location: body.location,
    price: +body.price,
    saved: false,
    createdAt: `${Date.now()}`,
    updatedAt: `${Date.now()}`,
    owner: {
      email: 'testuser@gamil.com',
      fullName: 'Test User',
      id: '10',
      location: 'fdsf',
      avatar:
        'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
      phone: 'sdfdfdfdsf',
      createdAt: 'dfsf',
      updatedAt: 'gksfngkf',
    },
  };
  TEST_PRODUCTS.push(newProduct);
  return {
    data: newProduct,
  };
}

export const CHATS = [
  {
    id: 387,
    productId: 33,
    ownerId: '10',
    createdAt: 22,
    updatedAt: 1685041046826,

    message: {
      id: 3384,
      chatId: 22,
      ownerId: '10',
      text: 'Hey, how are you, friend?',
      read: false,
      createdAt: 3232,
      updatedAt: 321321,
    },
    product: {
      id: 101010,
      ownerId: '10',
      title: 'Test product',
      description: 'Test product description',
      photos: [
        'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
      ],
      location: 'ladssd',
      price: 332,
      saved: false,
      createdAt: `${Date.now()}`,
      updatedAt: `${Date.now()}`,
      owner: {
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        id: '10',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
      },
    },

    participants: [
      {
        id: '10',
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
        ownProducts: {
          items: [
            {
              id: 'ASDSM',
              ownerId: '10',
              title: 'masdmsa',
              description: 'body.description',
              photos: ['body.images'],
              location: 'body.location',
              price: 44,
              saved: false,
              createdAt: `${Date.now()}`,
              updatedAt: `${Date.now()}`,
              owner: {
                email: 'testuser@gamil.com',
                fullName: 'Test User',
                id: '10',
                location: 'fdsf',
                avatar:
                  'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
                phone: 'sdfdfdfdsf',
                createdAt: 'dfsf',
                updatedAt: 'gksfngkf',
              },
            },
          ],
          searchItems: [],
        },
      },
      {
        id: '20',
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
        ownProducts: [
          {
            id: 'ASDSM',
            ownerId: '20',
            title: 'masdmsa',
            description: 'body.description',
            photos: ['body.images'],
            location: 'body.location',
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: 'testuser@gamil.com',
              fullName: 'Test User',
              id: '20',
              location: 'fdsf',
              avatar:
                'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
              phone: 'sdfdfdfdsf',
              createdAt: 'dfsf',
              updatedAt: 'gksfngkf',
            },
          },
        ],
      },
    ],
  },
  // chat 2
  {
    id: 307,
    productId: 33,
    ownerId: '20',
    createdAt: 22,
    updatedAt: 1682704857674,
    messages: {},
    message: {
      id: 3385,
      chatId: 22,
      ownerId: '20',
      text: 'Purus vitae placerat sollicitudin placerat dsad dsad ',
      read: true,
      createdAt: 3232,
      updatedAt: 321321,
    },
    product: {
      id: 2367,
      ownerId: '20',
      title: 'masdmsa',
      description: 'body.description',
      photos: [
        'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fexpoproject-aeb8be29-bf3a-4275-a960-54282c5f6b7a/ImagePicker/c3dbdf38-2c1f-463f-ba1e-97ca1d9188de.jpeg',
      ],
      location: 'body.location',
      price: 44,
      saved: false,
      createdAt: `${Date.now()}`,
      updatedAt: `${Date.now()}`,
      owner: {
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        id: '20',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
      },
    },

    participants: [
      {
        id: '10',
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
        ownProducts: [
          {
            id: 'ASDSM',
            ownerId: '10',
            title: 'masdmsa',
            description: 'body.description',
            photos: ['body.images'],
            location: 'body.location',
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: 'testuser@gamil.com',
              fullName: 'Test User',
              id: '10',
              location: 'fdsf',
              avatar:
                'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
              phone: 'sdfdfdfdsf',
              createdAt: 'dfsf',
              updatedAt: 'gksfngkf',
            },
          },
        ],
      },
      {
        id: '10',
        email: 'testuser@gamil.com',
        fullName: 'Test User',
        location: 'fdsf',
        avatar:
          'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
        phone: 'sdfdfdfdsf',
        createdAt: 'dfsf',
        updatedAt: 'gksfngkf',
        ownProducts: [
          {
            id: 'ASDSM',
            ownerId: '10',
            title: 'masdmsa',
            description: 'body.description',
            photos: ['body.images'],
            location: 'body.location',
            price: 44,
            saved: false,
            createdAt: `${Date.now()}`,
            updatedAt: `${Date.now()}`,
            owner: {
              email: 'testuser@gamil.com',
              fullName: 'Test User',
              id: '10',
              location: 'fdsf',
              avatar:
                'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
              phone: 'sdfdfdfdsf',
              createdAt: 'dfsf',
              updatedAt: 'gksfngkf',
            },
          },
        ],
      },
    ],
  },
];

export const MESSAGES = [
  {
    id: 3386,
    chatId: 22,
    ownerId: '20',
    text: 'Hello',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3387,
    chatId: 22,
    ownerId: '10',
    text: 'Lorem ipsum dolor sit amet',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3388,
    chatId: 22,
    ownerId: '10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3389,
    chatId: 22,
    ownerId: '20',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3390,
    chatId: 22,
    ownerId: '10',
    text: 'Hello',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3391,
    chatId: 22,
    ownerId: '20',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3392,
    chatId: 22,
    ownerId: '20',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3393,
    chatId: 22,
    ownerId: '10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3394,
    chatId: 22,
    ownerId: '20',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3395,
    chatId: 22,
    ownerId: '10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3396,
    chatId: 22,
    ownerId: '20',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
  {
    id: 3397,
    chatId: 22,
    ownerId: '10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',
    read: true,
    createdAt: 3232,
    updatedAt: 321321,
  },
];

console.log(MESSAGES.reverse());
